# Form implementation generated from reading ui file 'D:\Files of projects\Python\hour_track\hour_track\ui\about.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(300, 360)
        about.setMinimumSize(QtCore.QSize(300, 360))
        about.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(about)
        self.gridLayout.setContentsMargins(3, 0, 3, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=about)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "О программе"))
        self.label.setText(_translate("about", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">hourTack</span></p><p align=\"center\">Программа для ведения учёта и анализа проведённых учебных часов по дисциплинам в различных группах.</p><p align=\"right\"><br/><br/></p><p align=\"right\"><br/></p><p align=\"right\">GitHub: <a href=\"https://github.com/Cy-Nec/hour_track\"><span style=\" text-decoration: underline; color:#0000ff;\">source</span></a></p><p align=\"right\">© Protocol 418</p><p align=\"right\"><a href=\"https://github.com/Cy-Nec\"><span style=\" text-decoration: underline; color:#0000ff;\">Cy_Nec</span></a></p><p align=\"right\"><a href=\"https://github.com/taishakutenn\"><span style=\" text-decoration: underline; color:#0000ff;\">taishakutenn</span></a></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    about = QtWidgets.QDialog()
    ui = Ui_about()
    ui.setupUi(about)
    about.show()
    sys.exit(app.exec())
