# Form implementation generated from reading ui file 'D:\Files of projects\Python\hour_track\hour_track\ui\filterDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Filter(object):
    def setupUi(self, Dialog_Filter):
        Dialog_Filter.setObjectName("Dialog_Filter")
        Dialog_Filter.resize(460, 496)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog_Filter.setFont(font)
        Dialog_Filter.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_Filter)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog_Filter)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label1 = QtWidgets.QLabel(parent=self.frame)
        self.label1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label1.setObjectName("label1")
        self.verticalLayout_2.addWidget(self.label1)
        self.listW_groups = QtWidgets.QListWidget(parent=self.frame)
        self.listW_groups.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.listW_groups.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listW_groups.setObjectName("listW_groups")
        self.verticalLayout_2.addWidget(self.listW_groups)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame1 = QtWidgets.QFrame(parent=Dialog_Filter)
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label2 = QtWidgets.QLabel(parent=self.frame1)
        self.label2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label2.setObjectName("label2")
        self.verticalLayout.addWidget(self.label2)
        self.listW_groups_2 = QtWidgets.QListWidget(parent=self.frame1)
        self.listW_groups_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.listW_groups_2.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listW_groups_2.setObjectName("listW_groups_2")
        self.verticalLayout.addWidget(self.listW_groups_2)
        self.gridLayout.addWidget(self.frame1, 0, 1, 1, 1)
        self.frame2 = QtWidgets.QFrame(parent=Dialog_Filter)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Cancel = QtWidgets.QPushButton(parent=self.frame2)
        self.btn_Cancel.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_Cancel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.horizontalLayout.addWidget(self.btn_Cancel)
        self.btn_Accept = QtWidgets.QPushButton(parent=self.frame2)
        self.btn_Accept.setMinimumSize(QtCore.QSize(0, 32))
        self.btn_Accept.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btn_Accept.setObjectName("btn_Accept")
        self.horizontalLayout.addWidget(self.btn_Accept)
        self.gridLayout.addWidget(self.frame2, 1, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 3)

        self.retranslateUi(Dialog_Filter)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Filter)

    def retranslateUi(self, Dialog_Filter):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Filter.setWindowTitle(_translate("Dialog_Filter", "Фильтры"))
        self.label1.setText(_translate("Dialog_Filter", "Группы"))
        self.listW_groups.setSortingEnabled(True)
        self.label2.setText(_translate("Dialog_Filter", "Дисциплины"))
        self.listW_groups_2.setSortingEnabled(True)
        self.btn_Cancel.setText(_translate("Dialog_Filter", "Отменить"))
        self.btn_Accept.setText(_translate("Dialog_Filter", "Фильтровать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Filter = QtWidgets.QDialog()
    ui = Ui_Dialog_Filter()
    ui.setupUi(Dialog_Filter)
    Dialog_Filter.show()
    sys.exit(app.exec())
