# Form implementation generated from reading ui file 'D:\Files of projects\Python\hour_track\hour_track\ui\groupDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Group(object):
    def setupUi(self, Dialog_Group):
        Dialog_Group.setObjectName("Dialog_Group")
        Dialog_Group.resize(591, 438)
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog_Group.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_Group)
        self.gridLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_Edit = QtWidgets.QGroupBox(parent=Dialog_Group)
        self.groupBox_Edit.setObjectName("groupBox_Edit")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_Edit)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.groupBox_Edit)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Delete = QtWidgets.QPushButton(parent=self.frame)
        self.btn_Delete.setObjectName("btn_Delete")
        self.horizontalLayout.addWidget(self.btn_Delete)
        self.btn_Update = QtWidgets.QPushButton(parent=self.frame)
        self.btn_Update.setObjectName("btn_Update")
        self.horizontalLayout.addWidget(self.btn_Update)
        self.gridLayout.addWidget(self.frame, 6, 1, 1, 1)
        self.comboBox_Groups = QtWidgets.QComboBox(parent=self.groupBox_Edit)
        self.comboBox_Groups.setEditable(True)
        self.comboBox_Groups.setObjectName("comboBox_Groups")
        self.gridLayout.addWidget(self.comboBox_Groups, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.lineEdit_group = QtWidgets.QLineEdit(parent=self.groupBox_Edit)
        self.lineEdit_group.setObjectName("lineEdit_group")
        self.gridLayout.addWidget(self.lineEdit_group, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_Edit, 0, 1, 1, 1)
        self.listWidget_Groups = QtWidgets.QListWidget(parent=Dialog_Group)
        self.listWidget_Groups.setObjectName("listWidget_Groups")
        self.gridLayout_2.addWidget(self.listWidget_Groups, 0, 0, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.frame1 = QtWidgets.QFrame(parent=Dialog_Group)
        self.frame1.setObjectName("frame1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_RemoveLine = QtWidgets.QPushButton(parent=self.frame1)
        self.btn_RemoveLine.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_RemoveLine.setMaximumSize(QtCore.QSize(32, 32))
        self.btn_RemoveLine.setText("")
        self.btn_RemoveLine.setIconSize(QtCore.QSize(24, 24))
        self.btn_RemoveLine.setObjectName("btn_RemoveLine")
        self.horizontalLayout_2.addWidget(self.btn_RemoveLine)
        self.btn_AddLine = QtWidgets.QPushButton(parent=self.frame1)
        self.btn_AddLine.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_AddLine.setMaximumSize(QtCore.QSize(32, 32))
        self.btn_AddLine.setText("")
        self.btn_AddLine.setIconSize(QtCore.QSize(24, 24))
        self.btn_AddLine.setObjectName("btn_AddLine")
        self.horizontalLayout_2.addWidget(self.btn_AddLine)
        self.gridLayout_2.addWidget(self.frame1, 3, 0, 1, 1)
        self.frame2 = QtWidgets.QFrame(parent=Dialog_Group)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_Cancel = QtWidgets.QPushButton(parent=self.frame2)
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.horizontalLayout_3.addWidget(self.btn_Cancel)
        self.btn_Accept = QtWidgets.QPushButton(parent=self.frame2)
        self.btn_Accept.setObjectName("btn_Accept")
        self.horizontalLayout_3.addWidget(self.btn_Accept)
        self.gridLayout_2.addWidget(self.frame2, 2, 1, 1, 1)
        self.gridLayout_2.setRowStretch(1, 3)

        self.retranslateUi(Dialog_Group)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Group)

    def retranslateUi(self, Dialog_Group):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Group.setWindowTitle(_translate("Dialog_Group", "Группы"))
        self.groupBox_Edit.setTitle(_translate("Dialog_Group", "Редактирование"))
        self.btn_Delete.setText(_translate("Dialog_Group", "Удалить"))
        self.btn_Update.setText(_translate("Dialog_Group", "Обновить"))
        self.btn_Cancel.setText(_translate("Dialog_Group", "Отменить"))
        self.btn_Accept.setText(_translate("Dialog_Group", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Group = QtWidgets.QDialog()
    ui = Ui_Dialog_Group()
    ui.setupUi(Dialog_Group)
    Dialog_Group.show()
    sys.exit(app.exec())
