# Form implementation generated from reading ui file 'D:\Files of projects\Python\hour_track\hour_track\ui\newYearDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_NewYear(object):
    def setupUi(self, Dialog_NewYear):
        Dialog_NewYear.setObjectName("Dialog_NewYear")
        Dialog_NewYear.resize(384, 501)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog_NewYear)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog_NewYear)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_firstHalf = QtWidgets.QWidget()
        self.tab_firstHalf.setObjectName("tab_firstHalf")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_firstHalf)
        self.gridLayout.setObjectName("gridLayout")
        self.treeW_firstHalf = QtWidgets.QTreeWidget(parent=self.tab_firstHalf)
        self.treeW_firstHalf.setObjectName("treeW_firstHalf")
        self.gridLayout.addWidget(self.treeW_firstHalf, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_firstHalf, "")
        self.tab_SecondHalf = QtWidgets.QWidget()
        self.tab_SecondHalf.setObjectName("tab_SecondHalf")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_SecondHalf)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeW_SecondHalf = QtWidgets.QTreeWidget(parent=self.tab_SecondHalf)
        self.treeW_SecondHalf.setObjectName("treeW_SecondHalf")
        self.gridLayout_2.addWidget(self.treeW_SecondHalf, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_SecondHalf, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=Dialog_NewYear)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_loadFile = QtWidgets.QPushButton(parent=self.frame)
        self.btn_loadFile.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_loadFile.setFont(font)
        self.btn_loadFile.setObjectName("btn_loadFile")
        self.horizontalLayout.addWidget(self.btn_loadFile)
        self.btn_Cancel = QtWidgets.QPushButton(parent=self.frame)
        self.btn_Cancel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Cancel.setFont(font)
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.horizontalLayout.addWidget(self.btn_Cancel)
        self.btn_Accept = QtWidgets.QPushButton(parent=self.frame)
        self.btn_Accept.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_Accept.setFont(font)
        self.btn_Accept.setObjectName("btn_Accept")
        self.horizontalLayout.addWidget(self.btn_Accept)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(Dialog_NewYear)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog_NewYear)

    def retranslateUi(self, Dialog_NewYear):
        _translate = QtCore.QCoreApplication.translate
        Dialog_NewYear.setWindowTitle(_translate("Dialog_NewYear", "Новый год"))
        self.treeW_firstHalf.headerItem().setText(0, _translate("Dialog_NewYear", "Группа"))
        self.treeW_firstHalf.headerItem().setText(1, _translate("Dialog_NewYear", "Количество часов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_firstHalf), _translate("Dialog_NewYear", "Первое полугодие"))
        self.treeW_SecondHalf.headerItem().setText(0, _translate("Dialog_NewYear", "Группа"))
        self.treeW_SecondHalf.headerItem().setText(1, _translate("Dialog_NewYear", "Количество часов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_SecondHalf), _translate("Dialog_NewYear", "Второе полугодие"))
        self.btn_loadFile.setText(_translate("Dialog_NewYear", "Загрузить "))
        self.btn_Cancel.setText(_translate("Dialog_NewYear", "Отменить"))
        self.btn_Accept.setText(_translate("Dialog_NewYear", "Создать/Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_NewYear = QtWidgets.QDialog()
    ui = Ui_Dialog_NewYear()
    ui.setupUi(Dialog_NewYear)
    Dialog_NewYear.show()
    sys.exit(app.exec())
