# Form implementation generated from reading ui file 'D:\Files of projects\Python\hour_track\hour_track\ui\reportDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Report(object):
    def setupUi(self, Dialog_Report):
        Dialog_Report.setObjectName("Dialog_Report")
        Dialog_Report.resize(360, 447)
        Dialog_Report.setMinimumSize(QtCore.QSize(360, 0))
        Dialog_Report.setMaximumSize(QtCore.QSize(700, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(Dialog_Report)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog_Report)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeW_report = QtWidgets.QTreeWidget(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeW_report.setFont(font)
        self.treeW_report.setWordWrap(False)
        self.treeW_report.setObjectName("treeW_report")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.treeW_report.headerItem().setFont(2, font)
        self.verticalLayout.addWidget(self.treeW_report)
        self.btn_close = QtWidgets.QPushButton(parent=self.frame)
        self.btn_close.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_close.setFont(font)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog_Report)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Report)

    def retranslateUi(self, Dialog_Report):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Report.setWindowTitle(_translate("Dialog_Report", "Отчёт"))
        self.treeW_report.headerItem().setText(0, _translate("Dialog_Report", "Группа"))
        self.treeW_report.headerItem().setText(1, _translate("Dialog_Report", "Всего часов"))
        self.treeW_report.headerItem().setText(2, _translate("Dialog_Report", "Остаток часов"))
        self.btn_close.setText(_translate("Dialog_Report", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Report = QtWidgets.QDialog()
    ui = Ui_Dialog_Report()
    ui.setupUi(Dialog_Report)
    Dialog_Report.show()
    sys.exit(app.exec())
