# Form implementation generated from reading ui file 'D:\Files of projects\Python\hour_track\hour_track\ui\sortDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Sort(object):
    def setupUi(self, Dialog_Sort):
        Dialog_Sort.setObjectName("Dialog_Sort")
        Dialog_Sort.resize(321, 152)
        Dialog_Sort.setMaximumSize(QtCore.QSize(321, 152))
        font = QtGui.QFont()
        font.setPointSize(11)
        Dialog_Sort.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_Sort)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(parent=Dialog_Sort)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame1 = QtWidgets.QFrame(parent=self.frame)
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chkBox_group = QtWidgets.QCheckBox(parent=self.frame1)
        self.chkBox_group.setObjectName("chkBox_group")
        self.verticalLayout.addWidget(self.chkBox_group)
        self.chkBox_Subject = QtWidgets.QCheckBox(parent=self.frame1)
        self.chkBox_Subject.setObjectName("chkBox_Subject")
        self.verticalLayout.addWidget(self.chkBox_Subject)
        self.chkBox_Hours = QtWidgets.QCheckBox(parent=self.frame1)
        self.chkBox_Hours.setObjectName("chkBox_Hours")
        self.verticalLayout.addWidget(self.chkBox_Hours)
        self.horizontalLayout.addWidget(self.frame1)
        self.frame2 = QtWidgets.QFrame(parent=self.frame)
        self.frame2.setObjectName("frame2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rBtn_Down = QtWidgets.QRadioButton(parent=self.frame2)
        self.rBtn_Down.setObjectName("rBtn_Down")
        self.verticalLayout_2.addWidget(self.rBtn_Down)
        self.rBtn_Up = QtWidgets.QRadioButton(parent=self.frame2)
        self.rBtn_Up.setObjectName("rBtn_Up")
        self.verticalLayout_2.addWidget(self.rBtn_Up)
        self.horizontalLayout.addWidget(self.frame2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame3 = QtWidgets.QFrame(parent=Dialog_Sort)
        self.frame3.setObjectName("frame3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_Cancel = QtWidgets.QPushButton(parent=self.frame3)
        self.btn_Cancel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.horizontalLayout_2.addWidget(self.btn_Cancel)
        self.btn_Accept = QtWidgets.QPushButton(parent=self.frame3)
        self.btn_Accept.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_Accept.setObjectName("btn_Accept")
        self.horizontalLayout_2.addWidget(self.btn_Accept)
        self.gridLayout.addWidget(self.frame3, 2, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 8)

        self.retranslateUi(Dialog_Sort)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Sort)

    def retranslateUi(self, Dialog_Sort):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Sort.setWindowTitle(_translate("Dialog_Sort", "Сортировка"))
        self.chkBox_group.setText(_translate("Dialog_Sort", "По группам"))
        self.chkBox_Subject.setText(_translate("Dialog_Sort", "По предметам"))
        self.chkBox_Hours.setText(_translate("Dialog_Sort", "По количеству часов"))
        self.rBtn_Down.setText(_translate("Dialog_Sort", "По убыванию"))
        self.rBtn_Up.setText(_translate("Dialog_Sort", "По возрастанию"))
        self.btn_Cancel.setText(_translate("Dialog_Sort", "Отменить"))
        self.btn_Accept.setText(_translate("Dialog_Sort", "Сортировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Sort = QtWidgets.QDialog()
    ui = Ui_Dialog_Sort()
    ui.setupUi(Dialog_Sort)
    Dialog_Sort.show()
    sys.exit(app.exec())
